using UnityEngine;

/// <summary>
/// This script will move the object up and down.
/// It should be attached to the object that needs to move.
/// This script was generated by ChatGPT.
/// </summary>
public class ObjectMover : MonoBehaviour
{
    public float moveSpeed = 2.0f;
    public float moveDistance = 2.0f;

    private Vector3 initialPosition;

    private void Start()
    {
        initialPosition = transform.position;
    }

    private void Update()
    {
        // Use sine function to move the object up and down
        float newY = initialPosition.y + Mathf.Sin(Time.time * moveSpeed) * moveDistance;
        transform.position = new Vector3(transform.position.x, newY, transform.position.z);
    }
}