using UnityEngine;

// This script will move the object up and down
// This script was generated by ChatGPT
public class ObjectMover : MonoBehaviour
{
    public float moveSpeed = 2.0f;
    public float moveDistance = 2.0f;

    private Vector3 initialPosition;

    private void Start()
    {
        initialPosition = transform.position;
    }

    private void Update()
    {
        float newY = initialPosition.y + Mathf.Sin(Time.time * moveSpeed) * moveDistance;
        transform.position = new Vector3(transform.position.x, newY, transform.position.z);
    }
}